---
title: "Desarrollo de funciones"
format: html
editor: visual
---

1. Crea una función para descargar y leer los datos de estaciones.

```{r}
lectura_datos <- function(id, ruta){
  url_estacion <- paste0("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/", id, ".csv")
  if(!file.exists(ruta)){
    cli::cli_inform("El archivo no fue encontrado")
    download.file(url = url_estacion, destfile = ruta)
  } else{
    cli::cli_inform("El archivo ya existe en tu computadora")
  }
  datos <- readr::read_csv(ruta)
  return(datos)
}
```

2. Crea una función que se llame tabla_resumen_temperatura y que devuelva una tabla de resumen de la temperatura_abrigo_150cm para una o más estaciones. 

```{r}
tabla_resumen_temperatura <- function(datos){
  resumen <- datos |> 
    group_by(id) |> 
    summarise(
      temp_promedio = mean(temperatura_abrigo_150cm, na.rm = TRUE),
      temp_minima = min(temperatura_abrigo_150cm, na.rm = TRUE),
      temp_maxima = max(temperatura_abrigo_150cm, na.rm = TRUE)
    )
  return(resumen)
}
```


