---
title: "graficando_datos_meteorologicos1"
format: html
editor: visual
---

```{r}
library (tidyverse)
library (lubridate)
```

```{r}
metadatos <- read_csv("datos/crudos/metadatos.csv")
e046 <- read_csv("datos/crudos/estacion_046.csv")
e098 <- read_csv("datos/crudos/estacion_098.csv")
e437 <- read_csv("datos/crudos/estacion_437.csv")
e472 <- read_csv("datos/crudos/estacion_472.csv")
e910 <- read_csv("datos/crudos/estacion_910.csv")

datos_estaciones <- rbind(e046, e098, e437, e472, e910)
glimpse (datos_estaciones)
```

1.  Graficá la temperatura de abrigo para la estación NH0437 (tendrías que filtrar los datos para quedarte solo con esta estación). Sumá una regresión linea, ¿se mentiene constante la temperatura media con el tiempo o cambia?

```{r}
estacion_437 <- filter(datos_estaciones, id == "NH0437" &
                         !is.na(temperatura_abrigo_150cm))
glimpse (estacion_437)
```

```{r}
ggplot(data = estacion_437, 
       mapping = aes(x = temperatura_abrigo_150cm, 
                     y = year(fecha)) +
  geom_point(aes(colour = "red")) +
  geom_smooth (method= "lm", colour = "black") +
  labs (title= "Temperatura de la Estación NH0437 en función del tiempo",
        x= "Temperatura abrigo (°C)",
        y= "Tiempo (años)")
```
